### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by Vascher** [marcosmarp/hp-api#1]
On Sun 24 Apr the API went down, is it possible to pit it back online?

**Comment by marcosmarp** [comment]
Hey @Vascher, I can access the API normally. Could you describe your issue?

**Comment by Vascher** [comment]
I use it with fetch in javascript for a school project, if i load my website right now, it doesn’t show my data that i loaded in and als gives me a cors-error. I dont know yet how i can easily fix that, Thanks!

**Comment by marcosmarp** [comment]
@Vascher send me code or the repo and I'll take a look at it

**Comment by Vascher** [comment]
tibovanassche.be/harrypotter

**Comment by Vascher** [comment]
The code worked for a week or two until today. So i dont think it has anything to do with that. Another student of my class used the same one and got the same error.

**Comment by Vascher** [comment]
The link i sent is the site i use it for

**Comment by marcosmarp** [comment]
Hi @Vascher. Your website is consuming [Beth Fraser's API](https://github.com/KostaSav/hp-api), not mine. The link that your JS is calling is https://hp-api.herokuapp.com/api, while my API link is https://hp-api-marcosmarp.herokuapp.com/api

Feel free to use my API until Beth's one is up again.
